### ISSUE TITLE
Come up with  an API

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#2]
## General

* how do we store the required objects?
* what could be called a `parameter`, what a `model` here?
* what inputs do we want to give for creation of each?
* discuss below with examples.

## in particular

1. How do we represent \Psi_i, i.e. the set of all possible courses for student i?
1. how do we represent x_i, the courses chosen?
1. these considerations should be informed by how we want to address issue #4 

( notice you can display code nicely by using tripple back ticks before and after the code block - as described in your markdown cheat sheets! :-) )

**Comment by floswald** [comment]
```julia
mutable struct Student
    program :: String
    year :: Int
    time_constr :: Matrix
    prog_constr :: Matrix
    allocation :: Vector{Int}
end
```

**Comment by floswald** [comment]
* add funciton that reads data into this type.

**Comment by mdesevricourt** [comment]
I'm not sure I quite understand what you mean by a function that reads data into this type

**Comment by floswald** [comment]
solves by #14 
💯
