### ISSUE TITLE
think about data (preferences) input

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#5]
* what would be a good way to get student's preferences into your app?
* for example, assume we were given a csv file like

id |   course1  |  course2  |  course3  |  ... |
---|---|---|---|---|
1   |  100  |     20      |    30    |        ....|
2   |  89   |     95      |    13    |        ....|

how could we get that into our model? related to #2

**Comment by Gegas2231** [comment]
We could have a matrix for each student. Rows and columns represent courses, the values in the diagonal will represent individual utility for each course. Elements outside diagonal represent substitutes (-200) and complements (+200)

**Comment by Gegas2231** [comment]
I think the best way is using the matrix form that I mentioned. The diagonal elements will represent the individual utility, outside the diagonal substitutes and complements. Think on the following matrix for 3 courses.

`[80 10 -50; 10 90 0; -50 0 60]`

So each course will report 80, 90 and 60 utility units respectively. courses 1 and 2 together will report 20 points of additional utility (I write 10 but it'll make sense later). On the contrary, course 1 and 3 are substitutes, so together that will mean minus 100 points of utility. Course 2 and 3 together report no additional utility for the sake of the example. We can easily tune the additional values of utility to achieve the +200 and -200 from the paper.

With this matrix form, the computation of the utility becomes as follows:

X is a row vector of 0s or 1s. Say the utility Matrix is U.

The final utility will be X'*U*X. This matrix form is the reason why outside the diagonal we report the bonus utility divided by 2.

I checked with a simple example that this method works, can someone else check if what I'm writting above is true.

A problem with this approach is that our objective becomes nonlinear
