### ISSUE TITLE
fix clearing function

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#5]
[this](https://github.com/ScPo-CompEcon/CourseMatch.jl/blob/master/src/clearing.jl) needs to be cleaned up and put in a proper unit test in the `/test/` dir of the repo

**Comment by ghost** [comment]
i will work on this issue with Xiaojie

**Comment by jeannesorin** [comment]
@lorenzokaaks  and I have a clue if you need

**Comment by ghost** [comment]
As @jeannesorin and @lorenzokaaks  suggested I changed the output of the function to be the squareroot of the sum of squares instead of being an array of errors

**Comment by ghost** [comment]
created new branch with new function and test

**Comment by floswald** [comment]
when you are ready to share this addition you need to create a pull request from that new branch.
