### ISSUE TITLE
define function N(p) that returns a set of *neighboring* p's

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#6]
* page 13
* should be the union of
    1. gradient neighbors: 
        >a course that is over- subscribed by four seats will see its price raised twice as much as a course over-subscribed by two seats, and the neighborhood is formed by considering a number of potential step sizes along this gradient vector (we used up to 12). These steps can be thought of as a tˆatonnement performed by a Walrasian auctioneer.
    2. Individual adjustment neighbors:
        >Each neighbor of this type is the product of changing the price of a small set of courses. Let C be the number of under or over-subscribed courses. To limit the number of neighbors, min{C, 40} neighbors are created. If C <= 40, then each of the C neighbors adjusts the price of a single course. If 40 < C, then the C courses are evenly (and randomly) assigned to 40 neighbors. With each neighbor, the price of an over-subscribed course slated for adjustment is increased to reduce its demand by exactly one student, while the price of an under-subscribed course slated for adjustment is dropped to zero.
* input: current price vector p
* output: a set of K neighboring vectors, *neighboring* as above

**Comment by floswald** [comment]
there was some uncertainty last time about what they mean with "reducing demand by exactly one student". solve the entire demand problem again to find out how many students are discouraged?

**Comment by augustindao** [comment]
I used the method described in Othman (2010) with 2 optimizations, at the moment the function works. Only thing is I'm having trouble pushing the commit
