### ISSUE TITLE
translate algo 1 to julia pseudo code

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#7]
* the pseudo code in algo 1 is general
* copy this and replace the generic functions with their julia equivalents
* Of course much depends on what kind of datatypes we settle on in the end, but just the get a start regarding the control flow
* use `while`, `if else end` etc
* post solution here below

**Comment by mariecases** [comment]
Here's the code to prevent from needing to open in a PDF each time
<img width="447" alt="screen shot 2018-04-06 at 3 23 25 pm" src="https://user-images.githubusercontent.com/18401020/38423551-87aa2a18-39ae-11e8-8036-3c44192eab77.png">

**Comment by mariecases** [comment]
There's something I don't understand about the basics. In the paper, M is the number of courses offered and K is the number of courses a student has to take. So function N takes the initial guess of vector p (of size Mx1) and generates K neighbors ? If so, why K ?

**Comment by mariecases** [comment]
So far, at line 14 with a lot of functions to be replaced. Issues I set aside that will need to be addressed : 
- The big while loop that keeps track of computation time and stops when computation time exceeds the allotted time 
- l.13 : If d is not in tau. I imagine this may be a source of excess computation time. Does anyone know of a function that finds the intersection of two arrays by colum ?

**Comment by mariecases** [comment]
So it's pretty close. There are just a couple of issues, but the two big ones from above remain. 

As an idea for the do until currenttime > t, we could do something like the following : 
```
c=0
rightnow = Dates.Time(now())
t = 10 #in seconds for now
while Dates.second((Dates.Time(now()) - rightnow)) < t
    #Above, (Dates.Time(now()) - rightnow) is of type Nanosecond. We need this 
    #to be a number type in seconds (or minutes, seconds to see if the loop works).
    c = c + 1
end
```
We aren't sure this would work, but as mentioned, we're having an issue with type here so we can't even test. Any ideas ?

**Comment by mdesevricourt** [comment]
What I propose for the while loop with current time:

`
c=0
starttime = Dates.Time(now())
t = 10 #in seconds for now
while (now() - starttime).value < t *1000 #as now() - starttime is in milliseconds
    c = c + 1
end

`

Marie, is that helping?

**Comment by mdesevricourt** [comment]
For the second issue, it really is a matter of what type \tau and d are gonna be. 

I have an example here, but maybe there's something I am not seeing: 
Let's say we have two courses and that for the moment, we have two demand vectors in our tabu list

'''julia
d1 = [0,1]
d2 = [1,0]
tau = [d1, d2]
#we want to do something if another demand vector generated by a price vector, let's say d3, is not in tau
d3 = [1,1]
if !(d3 in tau)
   #  do something 
end
'''
